export const BUSINESS_DATA_CATEGORIES = [
  { value: "accounting", label: "Accounting" },
  { value: "airport", label: "Airports" },
  { value: "amusement_park", label: "Amusement parks" },
  { value: "aquarium", label: "Aquariums" },
  { value: "art_gallery", label: "Art galleries" },
  { value: "atm", label: "ATMs" },
  { value: "bakery", label: "Bakeries" },
  { value: "bank", label: "Banks" },
  { value: "bar", label: "Bars" },
  { value: "beauty_salon", label: "Beauty salons" },
  { value: "bicycle_store", label: "Bicycle stores" },
  { value: "book_store", label: "Book stores" },
  { value: "bowling_alley", label: "Bowling alleys" },
  { value: "bus_station", label: "Bus stations" },
  { value: "cafe", label: "Cafes" },
  { value: "campground", label: "Campgrounds" },
  { value: "car_dealer", label: "Car dealers" },
  { value: "car_rental", label: "Car rentals" },
  { value: "car_repair", label: "Car repair shops" },
  { value: "car_wash", label: "Car washes" },
  { value: "casino", label: "Casinos" },
  { value: "cemetery", label: "Cemeteries" },
  { value: "church", label: "Churches" },
  { value: "city_hall", label: "City halls" },
  { value: "clothing_store", label: "Clothing stores" },
  { value: "convenience_store", label: "Convenience stores" },
  { value: "courthouse", label: "Courthouses" },
  { value: "dentist", label: "Dentists" },
  { value: "department_store", label: "Department stores" },
  { value: "doctor", label: "Doctors" },
  { value: "drugstore", label: "Drugstores" },
  { value: "electrician", label: "Electricians" },
  { value: "electronics_store", label: "Electronics stores" },
  { value: "embassy", label: "Embassies" },
  { value: "fire_station", label: "Fire stations" },
  { value: "florist", label: "Florists" },
  { value: "funeral_home", label: "Funeral homes" },
  { value: "furniture_store", label: "Furniture stores" },
  { value: "gas_station", label: "Gas stations" },
  { value: "gym", label: "Gyms" },
  { value: "hair_care", label: "Hair care" },
  { value: "hardware_store", label: "Hardware stores" },
  { value: "hindu_temple", label: "Hindu temples" },
  { value: "home_goods_store", label: "Home goods stores" },
  { value: "hospital", label: "Hospitals" },
  { value: "insurance_agency", label: "Insurance agencies" },
  { value: "jewelry_store", label: "Jewelry stores" },
  { value: "laundry", label: "Laundries" },
  { value: "lawyer", label: "Lawyers" },
  { value: "library", label: "Libraries" },
  { value: "light_rail_station", label: "Light rail stations" },
  { value: "liquor_store", label: "Liquor stores" },
  { value: "local_government_office", label: "Local government offices" },
  { value: "locksmith", label: "Locksmiths" },
  { value: "lodging", label: "Hotels and lodging" },
  { value: "meal_delivery", label: "Meal delivery" },
  { value: "meal_takeaway", label: "Meal takeaway" },
  { value: "mosque", label: "Mosques" },
  { value: "movie_rental", label: "Movie rentals" },
  { value: "movie_theater", label: "Movie theaters" },
  { value: "moving_company", label: "Moving companies" },
  { value: "museum", label: "Museums" },
  { value: "night_club", label: "Night clubs" },
  { value: "painter", label: "Painters" },
  { value: "park", label: "Parks" },
  { value: "parking", label: "Parking" },
  { value: "pet_store", label: "Pet stores" },
  { value: "pharmacy", label: "Pharmacies" },
  { value: "physiotherapist", label: "Physiotherapists" },
  { value: "plumber", label: "Plumbers" },
  { value: "police", label: "Police stations" },
  { value: "post_office", label: "Post offices" },
  { value: "primary_school", label: "Primary schools" },
  { value: "real_estate_agency", label: "Real estate agencies" },
  { value: "restaurant", label: "Restaurants" },
  { value: "roofing_contractor", label: "Roofing contractors" },
  { value: "rv_park", label: "RV parks" },
  { value: "school", label: "Schools" },
  { value: "secondary_school", label: "Secondary schools" },
  { value: "shoe_store", label: "Shoe stores" },
  { value: "shopping_mall", label: "Shopping malls" },
  { value: "spa", label: "Spas" },
  { value: "stadium", label: "Stadiums" },
  { value: "storage", label: "Storage" },
  { value: "store", label: "Stores" },
  { value: "subway_station", label: "Subway stations" },
  { value: "supermarket", label: "Supermarkets" },
  { value: "synagogue", label: "Synagogues" },
  { value: "taxi_stand", label: "Taxi stands" },
  { value: "tourist_attraction", label: "Tourist attractions" },
  { value: "train_station", label: "Train stations" },
  { value: "transit_station", label: "Transit stations" },
  { value: "travel_agency", label: "Travel agencies" },
  { value: "university", label: "Universities" },
  { value: "veterinary_care", label: "Veterinary care" },
  { value: "zoo", label: "Zoos" }
] as const;

export const BUSINESS_DATA_CATEGORY_VALUES: ReadonlySet<string> = new Set(
  BUSINESS_DATA_CATEGORIES.map((category) => category.value)
);
