/** Official homepages for compare-page CTAs when no referral link exists. */
export const OFFICIAL_PRODUCT_URLS: Record<string, string> = {
  Adobe: "https://www.adobe.com/",
  "Adobe Express": "https://www.adobe.com/express/",
  Ahrefs: "https://ahrefs.com/",
  Airtable: "https://airtable.com/",
  AWS: "https://aws.amazon.com/",
  "AWS CloudFront": "https://aws.amazon.com/cloudfront/",
  "AWS Lambda": "https://aws.amazon.com/lambda/",
  Beehiiv: "https://www.beehiiv.com/",
  BigQuery: "https://cloud.google.com/bigquery",
  Buffer: "https://buffer.com/",
  Canva: "https://www.canva.com/",
  ChatGPT: "https://chatgpt.com/",
  Claude: "https://claude.ai/",
  Clearscope: "https://www.clearscope.io/",
  Cloudflare: "https://www.cloudflare.com/",
  "Cloudflare Workers": "https://workers.cloudflare.com/",
  ConvertKit: "https://kit.com/",
  Cursor: "https://cursor.com/",
  DigitalOcean: "https://www.digitalocean.com/",
  Firebase: "https://firebase.google.com/",
  Frase: "https://www.frase.io/",
  Ghost: "https://ghost.org/",
  "GitHub Copilot": "https://github.com/features/copilot",
  "Google Analytics 4": "https://analytics.google.com/",
  "Google Workspace": "https://workspace.google.com/",
  Gumroad: "https://gumroad.com/",
  Hootsuite: "https://www.hootsuite.com/",
  Hotjar: "https://www.hotjar.com/",
  Jasper: "https://www.jasper.ai/",
  Klaviyo: "https://www.klaviyo.com/",
  Loom: "https://www.loom.com/",
  Mailchimp: "https://mailchimp.com/",
  Matomo: "https://matomo.org/",
  Mediavine: "https://www.mediavine.com/",
  "Microsoft Clarity": "https://clarity.microsoft.com/",
  Moz: "https://moz.com/",
  Neon: "https://neon.tech/",
  Netlify: "https://www.netlify.com/",
  Notion: "https://www.notion.so/",
  Paddle: "https://www.paddle.com/",
  Pipedrive: "https://www.pipedrive.com/",
  PlanetScale: "https://planetscale.com/",
  Plausible: "https://plausible.io/",
  Railway: "https://railway.app/",
  Render: "https://render.com/",
  Riverside: "https://riverside.fm/",
  Semrush: "https://www.semrush.com/",
  Shopify: "https://www.shopify.com/",
  Sitebulb: "https://sitebulb.com/",
  Snowflake: "https://www.snowflake.com/",
  SpyFu: "https://www.spyfu.com/",
  "Screaming Frog": "https://www.screamingfrog.co.uk/seo-spider/",
  Stripe: "https://stripe.com/",
  Substack: "https://substack.com/",
  Supabase: "https://supabase.com/",
  Surfer: "https://surferseo.com/",
  Ubersuggest: "https://neilpatel.com/ubersuggest/",
  Vercel: "https://vercel.com/",
  Webflow: "https://webflow.com/",
  WooCommerce: "https://woocommerce.com/",
  WordPress: "https://wordpress.org/",
  Yoast: "https://yoast.com/",
  Zoho: "https://www.zoho.com/"
};

export function getOfficialProductUrl(product: string) {
  return OFFICIAL_PRODUCT_URLS[product] ?? null;
}
